# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hyperspectral.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1140, 900)
        Dialog.setMinimumSize(QtCore.QSize(1140, 900))
        Dialog.setMaximumSize(QtCore.QSize(2000, 2000))
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(930, 570, 191, 41))
        self.pushButton.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.graphicsView = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(20, 40, 541, 511))
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(740, 570, 171, 41))
        self.pushButton_2.setStyleSheet("font: 8.5pt \"MS Shell Dlg 2\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(930, 620, 191, 51))
        self.pushButton_3.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 570, 211, 41))
        self.pushButton_4.setStyleSheet("font: 7pt \"MS Shell Dlg 2\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(200, 790, 161, 51))
        self.pushButton_5.setObjectName("pushButton_5")
        self.graphicsView_2 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_2.setGeometry(QtCore.QRect(580, 40, 541, 511))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(930, 680, 191, 51))
        self.pushButton_6.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalSlider = QtWidgets.QSlider(Dialog)
        self.horizontalSlider.setGeometry(QtCore.QRect(380, 580, 171, 21))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(240, 570, 321, 41))
        self.textEdit.setStyleSheet("")
        self.textEdit.setObjectName("textEdit")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox.setGeometry(QtCore.QRect(300, 570, 71, 41))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(20, 620, 341, 161))
        self.listWidget.setObjectName("listWidget")
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 790, 171, 51))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Dialog)
        self.pushButton_8.setGeometry(QtCore.QRect(930, 740, 191, 51))
        self.pushButton_8.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Dialog)
        self.pushButton_9.setGeometry(QtCore.QRect(930, 800, 191, 41))
        self.pushButton_9.setStyleSheet("font: 75 9pt \"MS Shell Dlg 2\";")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_11 = QtWidgets.QPushButton(Dialog)
        self.pushButton_11.setGeometry(QtCore.QRect(580, 570, 151, 41))
        self.pushButton_11.setStyleSheet("font: 75 8.5pt \"MS Shell Dlg 2\";")
        self.pushButton_11.setObjectName("pushButton_11")
        
        # Add reset button
        self.resetButton = QtWidgets.QPushButton(Dialog)
        self.resetButton.setGeometry(QtCore.QRect(1000, 470, 100, 30))
        self.resetButton.setText("Reset")
        self.resetButton.setStyleSheet("""
            QPushButton {
                background-color: #4CAF50;
                color: white;
                border: none;
                border-radius: 4px;
                padding: 5px;
                font-weight: bold;
                min-height: 30px;
            }
            QPushButton:hover {
                background-color: #45a049;
            }
            QPushButton:pressed {
                background-color: #3d8b40;
            }
        """)
        self.resetButton.setObjectName("resetButton")
        self.resetButton.raise_()
        
        # Create range button for graphicsView_2
        self.rangeButton = QtWidgets.QPushButton(Dialog)
        self.rangeButton.setGeometry(QtCore.QRect(1000, 500, 100, 30))
        self.rangeButton.setText("Set Range")
        self.rangeButton.setStyleSheet("""
            QPushButton {
                background-color: #4CAF50;
                color: white;
                border: none;
                border-radius: 4px;
                padding: 5px;
                font-weight: bold;
            }
            QPushButton:hover {
                background-color: #45a049;
            }
        """)
        self.rangeButton.setObjectName("rangeButton")
        self.rangeButton.raise_()
        
        self.listWidget_2 = QtWidgets.QListWidget(Dialog)
        self.listWidget_2.setGeometry(QtCore.QRect(370, 620, 541, 221))
        self.listWidget_2.setObjectName("listWidget_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(210, 790, 41, 51))
        self.label.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.textEdit.raise_()
        self.listWidget.raise_()
        self.pushButton.raise_()
        self.graphicsView.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.graphicsView_2.raise_()
        self.pushButton_6.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.horizontalSlider.raise_()
        self.doubleSpinBox.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.pushButton_9.raise_()
        self.pushButton_11.raise_()
        self.listWidget_2.raise_()
        self.label.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "RGB DISPLAY"))
        self.pushButton_2.setText(_translate("Dialog", "SEGMENTED SPECTRUM"))
        self.pushButton_3.setText(_translate("Dialog", "SELECT ROI"))
        self.pushButton_4.setText(_translate("Dialog", "UPLOAD FOLDER"))
        self.pushButton_5.setText(_translate("Dialog", "BACK"))
        self.pushButton_6.setText(_translate("Dialog", "SEGMENTATION"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:2px; margin-bottom:-2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; vertical-align:sub;\">   BAND</span></p></body></html>"))
        self.pushButton_7.setText(_translate("Dialog", "CLEAR ALL"))
        self.pushButton_8.setText(_translate("Dialog", "MASK DISPLAY"))
        self.pushButton_9.setText(_translate("Dialog", "EXPORT DATA"))
        self.pushButton_11.setText(_translate("Dialog", "ENTIRE SPECTRUM"))
        self.label.setText(_translate("Dialog", "⬅"))
